# Generated by Django 3.2.5 on 2021-08-07 09:35

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_datetime',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='updated_datetime',
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=mdeditor.fields.MDTextField(),
        ),
    ]
