# Generated by Django 3.2.5 on 2021-08-07 13:36

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210807_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(),
        ),
    ]
