# Generated by Django 3.2.5 on 2021-08-07 13:40

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210807_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='text',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
