# Generated by Django 3.2.5 on 2021-08-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210807_2240'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
